# Generated by Django 3.1.1 on 2020-09-21 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiffCoExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_id', models.IntegerField(blank=True, null=True)),
                ('input_excel', models.TextField(blank=True, null=True)),
                ('healthy_sample', models.IntegerField(blank=True, null=True)),
                ('disease_sample', models.IntegerField(blank=True, null=True)),
                ('pcritic_min', models.TextField(blank=True, null=True)),
                ('pcritic_max', models.TextField(blank=True, null=True)),
                ('healthy_normality_pvalue', models.TextField(blank=True, null=True)),
                ('disease_normality_pvalue', models.TextField(blank=True, null=True)),
                ('healthy_co_expression', models.JSONField(blank=True, null=True)),
                ('disease_co_expression', models.JSONField(blank=True, null=True)),
                ('healthy_diff_co_expression', models.JSONField(blank=True, null=True)),
                ('disease_diff_co_expression', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_coexp_id', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('mcode', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
