# Generated by Django 3.1.1 on 2020-09-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diffcoexpression',
            old_name='pcritic_max',
            new_name='disease_pcritic',
        ),
        migrations.RenameField(
            model_name='diffcoexpression',
            old_name='pcritic_min',
            new_name='healthy_pcritic',
        ),
    ]
