# Generated by Django 3.1.3 on 2021-02-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_network_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='diff',
            new_name='diffcoexp',
        ),
    ]
