# Generated by Django 3.1.3 on 2021-02-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210218_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='id',
        ),
        migrations.AlterField(
            model_name='network',
            name='diffcoexp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='diff_coexp_id', serialize=False, to='app.diffcoexpression'),
        ),
    ]
