# Generated by Django 3.1.3 on 2021-02-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210218_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='diffcoexp',
            new_name='diff_coexp',
        ),
        migrations.RemoveField(
            model_name='network',
            name='diff_coexp_id',
        ),
    ]
