# Generated by Django 3.1.3 on 2021-02-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210218_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='diff_coexp',
        ),
        migrations.AddField(
            model_name='network',
            name='diff_coexp_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='diffcoexp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diff_coexp_id', to='app.diffcoexpression'),
        ),
    ]
